# config/services.yaml
parameters:
    tmdb.api_key: '%env(TMDB_API_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $apiKey: '%tmdb.api_key%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # explicitly configure the TmdbClient to receive the API key
    App\Service\TmdbClient:
        arguments:
            $apiKey: '%tmdb.api_key%'

